### ISSUE TITLE
Compatability with polymorphic relationships?

### ISSUE THREAD

**Issue by tyler36** [michaeldyrynda/laravel-cascade-soft-deletes#23]
I installed the package successfully with one->many relationship child.
Cant seem to get it going with a polymorphic setup. Is it supported?

PS. Good work on the Laravel News podcast. It's great to hear a familiar accent in the Laravel world.

**Comment by michaeldyrynda** [comment]
Hey, it doesn't currently support cascades on polymorphic relationships.

I didn't implement it as it's not something easily implemented at the database level, which is what this package is trying to replicate. The cascade doesn't happen at the database level due to the constraint on the second column.

I'm happy for you to submit a PR to add the functionality in, being mindful of the fact that it's going to get unwieldy and slow at scale. Have a look at the pr-13 branch, which did some work around adding `BelongsToMany` support, which might be similar-ish to what you need to achieve the same for polymorphic relationships.

**Comment by tyler36** [comment]
Thanks for the reply. 
I didn't see anything about polymorphic relationships so I assumed I might have been doing something wrong.

**Comment by rs-sliske** [comment]
I havent tested this but i think pr #9 will have fixed the polymorphic relationships.
