### ISSUE TITLE
Restore event like delete

### ISSUE THREAD

**Issue by forxer** [michaeldyrynda/laravel-cascade-soft-deletes#4]
It would be nice to implement the same functionality for the restore event.

**Comment by michaeldyrynda** [comment]
It's an interesting consideration, given this is where soft and hard cascading deletes diverge.

When you're using cascading deletes at the database level, once a record is deleted, it's gone (unless you have a backup of the database).

With the soft delete, you have the benefit of it only being marked as deleted. That being the case, you have no way of knowing when a child record was deleted i.e. if it was deleted because the parent record was removed, or at some other time.

Unless you track this separately or make assumptions based on `deleted_at` values, a restore on the parent would restore all child records. I feel that this is something beyond the scope of this package.
